"use client";
import { ChangeEvent, useState } from "react";
import Link from "next/link";

type Mapping={name:string|null;phone:string|null;consent:string|null;source:string|null};
export default function ImportPage(){
 const[file,setFile]=useState<File|null>(null),[mapping,setMapping]=useState<Mapping|null>(null),[rows,setRows]=useState<Record<string,unknown>[]>([]),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState("");
 async function analyze(){if(!file)return;setBusy(true);setError("");setResult(null);try{const f=new FormData();f.append("file",file);const r=await fetch("/api/leads/preview-import",{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);setMapping(d.mapping);setRows(d.preview||[]);setTotal(d.totalRows||0)}catch(e:any){setError(e.message||"Unable to analyze file")}finally{setBusy(false)}}
 async function importFile(){if(!file||!mapping?.phone)return;setBusy(true);setError("");try{const f=new FormData();f.append("file",file);const endpoint=/\.xlsx?$/i.test(file.name)?"/api/leads/import-xlsx":"/api/leads/import-xlsx";const r=await fetch(endpoint,{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d)}catch(e:any){setError(e.message||"Import failed")}finally{setBusy(false)}}
 const fields=["name","phone","consent","source"];
 return <main className="shell"><header className="top"><div><div className="brand">Import & Map Leads</div><div className="label">Review automatic column mapping before importing</div></div><Link className="btn secondary" href="/leads">Lead Database</Link></header>
 <section className="card section"><h2>1. Upload file</h2><p className="label">Supported: <b>.xlsx, .xls, .csv</b></p><input type="file" accept=".csv,.xlsx,.xls" onChange={(e:ChangeEvent<HTMLInputElement>)=>{setFile(e.target.files?.[0]??null);setMapping(null);setRows([]);setResult(null);setError("")}}/>{file&&<p className="label">Selected: {file.name}</p>}<button className="btn" disabled={!file||busy} onClick={analyze}>{busy?"Analyzing…":"Analyze columns"}</button></section>
 {mapping&&<section className="card section"><h2>2. Confirm mapping</h2><table className="table"><thead><tr><th>WhatsappBulk field</th><th>Detected column</th></tr></thead><tbody>{fields.map(f=><tr key={f}><td>{f}</td><td>{mapping[f as keyof Mapping]??"Not found"}</td></tr>)}</tbody></table><p className="label">Detected {total.toLocaleString()} data rows. Preview below shows up to 10.</p><table className="table"><thead><tr>{Object.keys(rows[0]||{}).slice(0,6).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,10).map((r,i)=><tr key={i}>{Object.keys(rows[0]||{}).slice(0,6).map(k=><td key={k}>{String(r[k]??"")}</td>)}</tr>)}</tbody></table><button className="btn" disabled={busy||!mapping.phone} onClick={importFile}>{busy?"Importing…":"Confirm & Import"}</button>{!mapping.phone&&<p className="label">A phone/mobile column is required before importing.</p>}</section>}
 {error&&<section className="card section"><b>Error:</b> {error}</section>}{result&&<section className="card section"><h2>Import complete</h2><pre className="result">{JSON.stringify(result,null,2)}</pre></section>}
 <section className="card section"><b>Safety:</b> Importing records never grants WhatsApp consent. Only explicit consent makes a lead eligible for marketing.</section></main>}
