"use client";
import { ChangeEvent, useState } from "react";
import Link from "next/link";
function parseCSV(text:string){const lines=text.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const headers=lines[0].split(",").map(x=>x.trim().toLowerCase());return lines.slice(1).map(line=>{const values=line.split(",");return Object.fromEntries(headers.map((h,i)=>[h,(values[i]??"").trim()]))})}
export default function ImportPage(){
 const[file,setFile]=useState<File|null>(null),[rows,setRows]=useState<any[]>([]),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[type,setType]=useState("");
 async function previewFile(){if(!file)return;setResult(null);if(/\.xlsx?$/i.test(file.name)){setType("xlsx");setRows([]);setPreview(true);return}setRows(parseCSV(await file.text()));setType("csv");setPreview(true)}
 async function upload(){if(!file)return;setBusy(true);setResult(null);try{if(type==="xlsx"){const form=new FormData();form.append("file",file);const r=await fetch("/api/leads/import-xlsx",{method:"POST",body:form});setResult(await r.json())}else{const leads=rows.map(r=>({name:r.name||r.full_name||r.customer_name||"Customer",phone:r.phone||r.mobile||r.whatsapp,consent:r.consent,source:r.source||"CSV_IMPORT"}));const r=await fetch("/api/leads/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leads})});setResult(await r.json())}}catch{setResult({error:"Import failed"})}finally{setBusy(false)}}
 return <main className="shell"><header className="top"><div><div className="brand">Import Leads</div><div className="label">CSV or Excel customer database import</div></div><Link className="btn secondary" href="/leads">Lead Database</Link></header>
 <section className="card section"><h2>Upload file</h2><p className="label">Supported: <b>.csv, .xlsx, .xls</b>. Columns: name, phone/mobile/whatsapp, consent, source.</p><input type="file" accept=".csv,.xlsx,.xls" onChange={(e:ChangeEvent<HTMLInputElement>)=>{setFile(e.target.files?.[0]??null);setPreview(false);setRows([]);setResult(null)}}/>{file&&<p className="label">Selected: {file.name}</p>}<div className="actions" style={{marginTop:16}}><button className="btn secondary" disabled={!file||busy} onClick={previewFile}>Preview</button><button className="btn" disabled={!file||busy||(!rows.length&&type!=="xlsx")} onClick={upload}>{busy?"Importing…":"Import leads"}</button></div></section>
 {preview&&type==="xlsx"&&<section className="card section"><h2>Excel ready</h2><p className="label">The first worksheet will be processed on import. Excel rows are validated server-side before being saved.</p></section>}
 {preview&&type==="csv"&&<section className="card section"><h2>Preview</h2><p className="label">Showing first 10 of {rows.length.toLocaleString()} rows.</p><table className="table"><thead><tr><th>Name</th><th>Phone</th><th>Consent</th><th>Source</th></tr></thead><tbody>{rows.slice(0,10).map((r,i)=><tr key={i}><td>{r.name||r.full_name||r.customer_name||"Customer"}</td><td>{r.phone||r.mobile||r.whatsapp||"—"}</td><td>{r.consent||"No"}</td><td>{r.source||"CSV_IMPORT"}</td></tr>)}</tbody></table></section>}
 {result&&<section className="card section"><h2>Import result</h2><pre className="result">{JSON.stringify(result,null,2)}</pre></section>}
 <section className="card section"><b>Safety:</b> Importing data does not grant WhatsApp consent. Only explicit consent makes a lead eligible for marketing.</section></main>}
