import Link from "next/link";
import { prisma } from "@/lib/prisma";

async function stats(){try{const [leads,optedIn,campaigns,sent,failed]=await Promise.all([prisma.lead.count(),prisma.lead.count({where:{consent:true,optedOut:false}}),prisma.campaign.count(),prisma.message.count({where:{status:{in:["SENT","DELIVERED","READ"]}}}),prisma.message.count({where:{status:"FAILED"}})]);return{leads,optedIn,campaigns,sent,failed}}catch{return{leads:0,optedIn:0,campaigns:0,sent:0,failed:0}}}
function Nav(){return <nav className="nav"><Link className="active" href="/">Overview</Link><Link href="/leads">Leads</Link><Link href="/import">Import</Link><Link href="/campaigns">Campaigns</Link><Link href="/templates">Templates</Link><Link href="/reports">Reports</Link><Link href="/settings">Settings</Link></nav>}
export default async function Home(){const s=await stats();const rate=s.leads?Math.round(s.optedIn/s.leads*100):0;return <main className="shell"><header className="top"><div><div className="brand">WhatsAppBulk <span className="version">V2</span></div><div className="label">Consent-first WhatsApp campaign manager</div></div><div className="actions"><span className="badge">COMPLIANCE FIRST</span><form action="/api/auth/logout" method="post"><button className="btn secondary" type="submit">Sign out</button></form></div></header><Nav/>
<section className="grid"><div className="card"><div className="label">Total leads</div><div className="metric">{s.leads.toLocaleString()}</div></div><div className="card"><div className="label">Eligible WhatsApp leads</div><div className="metric">{s.optedIn.toLocaleString()}</div><div className="label">{rate}% of database</div></div><div className="card"><div className="label">Campaigns</div><div className="metric">{s.campaigns.toLocaleString()}</div></div><div className="card"><div className="label">Messages processed</div><div className="metric">{s.sent.toLocaleString()}</div><div className="label">{s.failed.toLocaleString()} failed</div></div></section>
<section className="card section"><div className="top" style={{marginBottom:0}}><div><h2>Campaign workflow</h2><div className="label">Move from lead capture to approved-template delivery.</div></div><Link className="btn" href="/campaigns">Create campaign</Link></div><div className="miniGrid grid" style={{marginTop:16}}><div><strong>01</strong><div>Build audience</div><span className="ok">{s.optedIn.toLocaleString()} eligible</span></div><div><strong>02</strong><div>Choose template</div><span className="ok">READY</span></div><div><strong>03</strong><div>Review campaign</div><span className="ok">REQUIRED</span></div><div><strong>04</strong><div>Send via Cloud API</div><span className="warn">CONFIGURE</span></div></div></section>
<section className="kpiRow"><div className="card section"><h2>Consent health</h2><div className="label">Eligible audience vs total imported leads</div><div className="progress"><div style={{width:`${rate}%`}}/></div><b>{rate}% eligible</b><div className="actions" style={{marginTop:14}}><Link className="btn secondary" href="/leads">View leads</Link><Link className="btn secondary" href="/import">Import more</Link></div></div><div className="card section"><h2>System readiness</h2><table className="table"><tbody><tr><td>Database</td><td className="ok">CONNECTED</td></tr><tr><td>Admin authentication</td><td className="ok">ENABLED</td></tr><tr><td>Consent enforcement</td><td className="ok">ENFORCED</td></tr><tr><td>WhatsApp Cloud API</td><td className="warn">CONFIGURE</td></tr></tbody></table></div></section>
<section className="card section"><h2>Compliance guardrails</h2><table className="table"><tbody><tr><td>WhatsApp consent required</td><td className="ok">ENFORCED</td></tr><tr><td>Opted-out contacts suppressed</td><td className="ok">ENFORCED</td></tr><tr><td>Meta-approved templates</td><td className="ok">REQUIRED</td></tr><tr><td>WhatsApp Web automation</td><td className="warn">NOT USED</td></tr></tbody></table></section></main>}