"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
type Lead={id:string;name:string;phone:string;consent:boolean;optedOut:boolean;source?:string|null;createdAt:string};
type Stats={total:number;consented:number;optedOut:number;notConsented:number};
function Nav(){return <nav className="nav"><Link href="/">Overview</Link><Link className="active" href="/leads">Leads</Link><Link href="/import">Import</Link><Link href="/campaigns">Campaigns</Link><Link href="/templates">Templates</Link><Link href="/reports">Reports</Link><Link href="/settings">Settings</Link></nav>}
export default function LeadsPage(){const[leads,setLeads]=useState<Lead[]>([]),[stats,setStats]=useState<Stats>({total:0,consented:0,optedOut:0,notConsented:0}),[status,setStatus]=useState("all"),[search,setSearch]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/leads?status=${status}&search=${encodeURIComponent(search)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load leads");setLeads(d.leads);setStats(d.stats)}catch(e:any){setError(e.message||"Unable to load leads")}finally{setLoading(false)}}useEffect(()=>{load()},[status]);const rate=stats.total?Math.round(stats.consented/stats.total*100):0;return <main className="shell"><header className="top"><div><div className="brand">Lead Database <span className="version">V2</span></div><div className="label">One place to manage imported customers, consent and suppression.</div></div><Link className="btn" href="/import">+ Import leads</Link></header><Nav/>
<section className="stats"><div className="card stat"><div className="label">Total leads</div><div className="value">{stats.total.toLocaleString()}</div></div><div className="card stat"><div className="label">WhatsApp eligible</div><div className="value">{stats.consented.toLocaleString()}</div><div className="label">{rate}% consent rate</div></div><div className="card stat"><div className="label">Not consented</div><div className="value">{stats.notConsented.toLocaleString()}</div></div><div className="card stat"><div className="label">Opted out</div><div className="value">{stats.optedOut.toLocaleString()}</div></div></section>
<section className="card section"><div className="toolbar"><input className="input" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search name or phone"/><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All leads</option><option value="consented">WhatsApp eligible</option><option value="not_consented">Not consented</option><option value="opted_out">Opted out</option></select><button className="btn" onClick={load}>{loading?"Searching…":"Search"}</button></div>{error&&<div className="error" style={{marginTop:14}}>{error}</div>}<div style={{overflowX:"auto",marginTop:14}}><table className="table"><thead><tr><th>Name</th><th>Phone</th><th>WhatsApp status</th><th>Source</th><th>Added</th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><b>{l.name}</b></td><td>{l.phone}</td><td>{l.optedOut?<span className="warn">OPTED OUT</span>:l.consent?<span className="ok">ELIGIBLE</span>:<span className="label">NOT CONSENTED</span>}</td><td>{l.source??"—"}</td><td>{new Date(l.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>{!leads.length&&!loading&&<p className="label">No leads found for this filter.</p>}</section>
<section className="card section"><h2>Audience rule</h2><div className="label">Only leads marked as consented and not opted out can enter a WhatsApp marketing campaign.</div><div className="progress"><div style={{width:`${rate}%`}}/></div><b>{stats.consented.toLocaleString()} eligible</b> <span className="label">out of {stats.total.toLocaleString()} total</span></section></main>}